version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/simple-cicd-app
    overwrite: yes

permissions:
  - object: /var/www/html/simple-cicd-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ec2-user